packages/graphql-typescript-definitions/src/print/document/index.ts
packages/graphql-typescript-definitions/src/print/document/language.ts
packages/graphql-typescript-definitions/src/print/document/utilities.ts
packages/graphql-typescript-definitions/test/document.test.ts

Our type generation had a weird edge case that breaks: when you have a union type, and multiple members of that union each have a field whose name matches between them, we generate a non-unique interface name. This PR namespaces all fields under unions in order to avoid such conflicts (see the added test for details).
cc/ @tsov since this was uncovered by online store [here](https://github.com/Shopify/online-store-web/pull/586/files).

Fix naming of types for fields nested under unions

---

packages/graphql-validate-fixtures/src/cli.ts
packages/graphql-validate-fixtures/test/__snapshots__/cli.test.ts.snap
packages/graphql-validate-fixtures/test/cli.test.ts

Part of https://github.com/Shopify/sewing-kit/issues/820
Adds a flag to conditionally show the `Pass`/valid fixtures, otherwise, do not output those.

Add `showPasses` argument

---

packages/graphql-typescript-definitions/src/index.ts
packages/graphql-typescript-definitions/test/__snapshots__/cli.test.ts.snap
packages/graphql-typescript-definitions/test/cli.test.ts
packages/graphql-typescript-definitions/test/fixtures/duplicate-names/documents/Query1/FindPeopleQuery.graphql
packages/graphql-typescript-definitions/test/fixtures/duplicate-names/documents/Query1/FindPersonsQuery.graphql
packages/graphql-typescript-definitions/test/fixtures/duplicate-names/documents/Query2/FindPersonQuery.graphql
packages/graphql-typescript-definitions/test/fixtures/duplicate-names/schema.graphql

Branches from https://github.com/Shopify/graphql-tools-web/pull/13#issuecomment-415279569
Part of Shopify/sewing-kit#811
Adds an error for when multiple queries share the same name. 
**Question:** Should we crash or just log the error?
```shell
ERROR  Graphql operations must have unique names. Found 2 or more operations with the name "FindPerson"
```
----
(may vary depeding on where you store project locally)
1. run `yarn build` from the root of this repo.
2. copy the built source to web `cp -R packages/graphql-typescript-definitions/lib/* ~/src/github.com/Shopify/web/node_modules/\@shopify/sewing-kit/node_modules/graphql-typescript-definitions/lib/
`
----
Screenshot for reference

Error on duplicate query names

---

README.md
packages/graphql-typescript-definitions/package.json
packages/graphql-typescript-definitions/src/cli.ts
packages/graphql-typescript-definitions/src/index.ts
packages/graphql-typescript-definitions/test/__snapshots__/cli.test.ts.snap
packages/graphql-typescript-definitions/test/cli.test.ts
packages/graphql-typescript-definitions/test/fixtures/all-clear/.graphqlconfig
packages/graphql-typescript-definitions/test/fixtures/duplicate-names/.graphqlconfig
packages/graphql-typescript-definitions/test/fixtures/malformed-query/.graphqlconfig
packages/graphql-typescript-definitions/test/fixtures/missing-schema/.graphqlconfig
packages/graphql-typescript-definitions/test/fixtures/missing-types/.graphqlconfig
packages/graphql-typescript-definitions/test/fixtures/multiple-schemas/.graphqlconfig
packages/graphql-typescript-definitions/test/fixtures/multiple-schemas/schema1/documents/Fragment.graphql
packages/graphql-typescript-definitions/test/fixtures/multiple-schemas/schema1/documents/Query.graphql
packages/graphql-typescript-definitions/test/fixtures/multiple-schemas/schema1/schema.graphql
packages/graphql-typescript-definitions/test/fixtures/multiple-schemas/schema2/documents/Fragment.graphql
packages/graphql-typescript-definitions/test/fixtures/multiple-schemas/schema2/documents/Query.graphql
packages/graphql-typescript-definitions/test/fixtures/multiple-schemas/schema2/schema.graphql
tsconfig.json
yarn.lock

Prior to this PR, this tool was only capable of processing a single schema within a workspace. The [Prisma `.graphqlconfig` (`graphql-config`)](https://github.com/prisma/graphql-config) format is gaining community support (see the [VSCode extension](https://github.com/prisma/vscode-graphql)) and is much more expressive, specifically in handling multiple schemas. This PR is mostly a drop in replacement, only requiring a small migration from the old `.gqlconfig` to the new `.graphqlconfig` format on consumer projects.
The intergration of `graphql-config` essentially builds a workspace `GraphQLConfig` and queries this instance whenever we want to process a graphql file (query, mutation, fragment, or schema). The top level config instance holds a collection of projects, each project is linked …

adding support for multiple schemas

---

packages/graphql-tool-utilities/README.md
packages/graphql-tool-utilities/ast.ts
packages/graphql-tool-utilities/package.json
packages/graphql-tool-utilities/polyfills.ts
packages/graphql-typescript-definitions/src/index.ts
packages/graphql-typescript-definitions/src/print/document/language.ts
packages/graphql-validate-fixtures/src/validate.ts
yarn.lock

our tooling is using `graphql@^0.13.0` and `apollo-codegen@^0.19.0` is using `graphql@^0.12.0`.
I am extending the built-in legacy types from `apollo-codegen` with some type overrides to improve the shape in some areas where the official types are lacking. I also had to patch a few places that were expecting slightly incorrect types and also forward propagating our internal types on collections to simplify type inference for consumers.
I had to add a new polyfill for `Array.flatmap` to support the `transformSelectionSetToLegacyIR` implementation.
I reduced the typing of `operationType` from a literal string union to just `string` (aligned with the built-in types) as we don't actually do any checking against this type anyways.

upgrading apollo-codegen to 0.20.2

---

packages/graphql-tool-utilities/README.md
packages/graphql-tool-utilities/augmentations.ts
packages/graphql-tool-utilities/config.ts
packages/graphql-tool-utilities/package.json
packages/graphql-typescript-definitions/src/index.ts

consolidating `graphql-config` functions from `graphql-typescript-definitions` into `graphql-tool-utilities`.  This will be in preparation for #21 to start consuming common `graphql-config` related functions.

refactoring graphql functions

---

.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json

* updating `settings.json` so that `jest` uses our `config.json`
* adding `launch.json` config so that `vscode-jest` supports debugger integration
* ading `extensions.json` to recommend `vscode-jest` (as well as `eslint` and `prettier` extensions)

adding support for vscode-jest

---

packages/graphql-tool-utilities/package.json
packages/graphql-typescript-definitions/package.json
packages/graphql-validate-fixtures/package.json
yarn.lock

`apollo-codegen` is a monorepo that pulls in a lot of extra dependencies that are not necessary, so we can reduce this to just `apollo-codegen-core`.
additionally, consolidating which version of the graphql tooling we are using to simplify versioning in versions in consumers. This should essentially be a no-op change that will only remove no longer necessary packages from the dependency chain.
* `@types/graphql` is upgraded to `0.13.4`
* packages in this repo no longer directly depend on `@types/graphql`, `graphql`, or `graphql-config` (now provided through `graphql-tool-utilities`)

fixing dependencies for graphql-tools-utilities

---

packages/graphql-tool-utilities/README.md
packages/graphql-typescript-definitions/README.md

Now that the `graphql-tool-utilities` package is the single source for `graphql-config` handling, we can add common documentation to this package and link to this documentation from other packages.

moving common graphql-config documentation to graphql-tool-utilities

---

packages/graphql-tool-utilities/augmentations.ts

`GraphQLProjectConfig.schemaPath` is [nullable](https://github.com/prisma/graphql-config/blob/master/src/GraphQLProjectConfig.ts#L92) because it's possible to [share a schema](https://github.com/prisma/graphql-config/blob/4c09eef3b97ebfbde6aa3710dfcfb1fe845f6d60/specification.md#default-configuration-properties) across multiple projects. Due to the typing used in `graphql-config` this results in the `schemaPath` having a nullable type. In practice, a project without a schema is not valid. In order to reduce boilerplate to guard against an invalid schema, a resolution function is added to the project to simplify _access or throw_ on the `schemaPath`.

adding augmentation to simplify project schemaPath resolution

---

packages/graphql-tool-utilities/index.ts

This PR is exporting the `graphql-config` helper functions so that consumers of this utility do not have to reach into the `config` module.  This PR also adds the augmentations for any consumers.

adding export surface for graphql-tool-utilities

---

packages/graphql-tool-utilities/augmentations.ts
packages/graphql-tool-utilities/config.ts
packages/graphql-typescript-definitions/src/index.ts
packages/graphql-typescript-definitions/test/__snapshots__/cli.test.ts.snap

Now that the tooling is relying completely on `graphql-config` for resolution of graphql entities, we are also at the mercy of `graphql-config` for error handling (which it performs less than stellar at). The `resolveSchemaPath` function should be the primary entrypoint for all consumers to resolve the `schemaPath` of a `GraphQLProjectConfig` instance, therefore we can additionally check the existence of the schema file and throw a more human readable error (instead of relying on node's readFile error, `ENOENT: ...`)
I went with `existsSync` to prevent requiring an additional `fs-extra` dependency and because it didn't force consumers to use async functions. Open to change suggestions.

unifying error handling of missing schema files

---

packages/graphql-tool-utilities/augmentations.ts
packages/graphql-tool-utilities/config.ts
packages/graphql-tool-utilities/index.ts
packages/graphql-typescript-definitions/src/index.ts

This function was added to simplify fully qualified resolution of paths relative to the `graphql-config` file. `GraphQLProjectConfig` already exposes this functionality wtih `resolveConfigPath`. This PR is refactoring usages of `getGraphQLFilePath` with `resolveConfigPath`.
this will conflict slightly with #37 and can be resolved by taking the change in #37

Remove getGraphQLFilePath function

---

packages/graphql-typescript-definitions/README.md
packages/graphql-typescript-definitions/src/index.ts
packages/graphql-typescript-definitions/test/__snapshots__/cli.test.ts.snap
packages/graphql-typescript-definitions/test/cli.test.ts
packages/graphql-typescript-definitions/test/fixtures/graphql-schema/.graphqlconfig
packages/graphql-typescript-definitions/test/fixtures/graphql-schema/documents/Query.graphql
packages/graphql-typescript-definitions/test/fixtures/graphql-schema/schema.graphql
packages/graphql-typescript-definitions/test/index.test.ts

This PR removes what was left of legacy graphql file reading in `graphql-typescript-definitions` to process changes to the graphql schema file. We now rely entirely on the `graphql-config` instance by using the `getSchema()` function. This resolves #32
The `chokidar` file watchers and the `glob` function now respect `excludes` defined in the `graphql-config` file. Each project now produces its own pair of `chokidar` watchers (one for schema and one for documents). Similarly, globbing now occurs on a per-project basis. This allows projects to specifically cover only the files they want linked to a schema. This resolves #31 
`chokidar` no longer generates events on startup. Setting the `ignoreInitial` option when we setup `chokidar` watchers prevents file add events from being emitted on …

using graphql-config for all schema file handling

---

packages/graphql-tool-utilities/config.ts

the previous `glob` import was taking advantage of `esModuleInterop` which may not be available in consumers' TypeScript configuration. By using an `import = require` we can avoid imposing this requirement.

fixing glob import for wider typescript configuration support

---

packages/graphql-tool-utilities/augmentations.ts

adds an optional `mustExist` parameter to `resolveSchemaPath` to opt out the file system check if the file exists. This is useful for consumers of this function who intend to create or delete the file and don't necessarily care if it exists yet, but rather just want to know where it should exist.

adding option to opt out of schemaPath file existence validation

---

packages/graphql-typed/package.json

updating to a specific version (`0.13.2`) to be consistent with other packages. We were already pulling in `0.13.2` but now consumers of this package will not possibly duplicate `graphql`.

fixing graphql version graphql-typed 

---

package.json

shipit won't support yarn 1.10.1 yet, so we'll reduce the `engine` requirements for the time being.

reducing yarn engine requirement to satisfy shipit

---

packages/graphql-typed/.npmignore

this will prevent the `index.ts` from being published to npm.

adding .npmignore file to graphql-typed

---

packages/graphql-fixtures/src/fill.ts
packages/graphql-fixtures/tests/fill.test.ts

Items of a list type were returning the same data, which does not properly represent fake a real response. This PR looks for List types and adds the index of the field to the end of the `responseName` in order to force a different value for each field. I am open to a better ways to achieve this.

Fixes non-unique List responses

---

packages/graphql-fixtures/package.json
packages/graphql-typescript-definitions/package.json

`graphql-typed` received [a version bump](https://github.com/Shopify/graphql-tools-web/commit/3d22e2c2f20c5c2e8d149fd6b77053e1463dd70f#diff-1e5458edf14329426cb89d760ebda6f9R3), but no corresponding bump was made to the `peerDependency` versions in related packages.

fixing incorrect graphql-typed peer dependency version

---

packages/graphql-tool-utilities/package.json
yarn.lock

`graphql-tool-utilities` requires at least `core-js@2.5.0` to [provide `flatMap`](https://github.com/zloirock/core-js/blob/v2.5.7/CHANGELOG.md#250---20170805).
This PR also consolidates all `core-js@^2.0.0` versions to `2.5.7`

upgrading core-js to 2.5.7

---

packages/graphql-typescript-definitions/src/print/document/language.ts
packages/graphql-typescript-definitions/test/document.test.ts

Currently, if a union or interface has all its possible types accounted for, or if there is only a single implementing type, we do not generate the "Other" type for a union or interface. That is, given the following schema:
```graphql
interface Animal {
legs: Int!
}
type Dog implements Animal {
legs: Int!
}
type Person {
name: String!
pets: [Animal]!
}
union Creature = Person | Dog
type Query {
creature: Creature
}
```
and this query:
```graphql
query MyQuery {
creature {
... on Dog { legs }
... on Person {
pets { ... on Dog { legs } }
}
}
}
```
We generate the following types:
```ts
namespace MyQueryData {
type CreatureDog = {} // for creature as Dog
type CreaturePerson = {} // for creature as Person
type CreaturePersonPets = {} // for creature.pets
}
```
This PR changes this type …

Generate "empty Other" type for unions and interfaces

---

.vscode/settings.json
packages/graphql-fixtures/src/fill.ts
packages/graphql-typed/index.ts

Adds a few helper types that will be used to make it possible to write functions that take either a regular document node or another object that extends `GraphQLOperation` (like the async query components from `@shopify/react-graphql`)

Add some helper types

---

packages/graphql-fixtures/package.json
packages/graphql-typescript-definitions/package.json

`peerDependencies` don't get auto-updated by lerna 🤕

fixing peer dependencies for graphql-typed and graphql-typescript-definitions

---

packages/graphql-typescript-definitions/README.md
packages/graphql-typescript-definitions/src/index.ts

I'm using the Builder API directly, but my project does not define a `.graphqlconfig` file, which means that I must create a temporary one just for the sake of running the type generation operation.
This change adds the possibility to provide a `config` option to the `Builder` options interface in order to provide your own custom `GraphQLConfig` instance.

Accept a config option

---

packages/graphql-mini-transforms/src/document.ts
packages/graphql-mini-transforms/src/webpack.ts
packages/graphql-mini-transforms/tests/webpack.test.ts

Fixes two issues with the Webpack transforms:
1. Now works correctly when `Buffer`s get involved
2. Now finds all imports, not just the first one (facepalm)

Fix Webpack transforms

---

.eslintrc.js
package.json
packages/graphql-fixtures/tests/fill.test.ts
packages/graphql-mini-transforms/package.json
packages/graphql-typescript-definitions/package.json
packages/graphql-typescript-definitions/src/index.ts
packages/graphql-typescript-definitions/src/print/document/context.ts
packages/graphql-typescript-definitions/src/print/document/utilities.ts
packages/graphql-validate-fixtures/package.json
yarn.lock

Related https://github.com/Shopify/eslint-plugin-shopify/pull/433
This PR upgrades this project to the latest `eslint` and `eslint-plugin-shopify`.

Update eslint-plugin-shopify v31.0.0

---

packages/graphql-fixtures/README.md
packages/graphql-fixtures/src/fill.ts

This new type construct simplifies how we can define the shape of mocked data that will be used for filling a GraphQL response. Instead of requiring all individual GraphQL document types, we can define the shape of mocked data via `type FooData = GraphQLFillerData<typeof fooQuery>`. This is particularly useful for building more composable filling wrapper functions where there are multiple schemas involved:
```tsx
function createFilledOperations({
fooData = {},
barData = {},
}: {
fooData?: GraphQLFillerData<typeof fooQuery>,
barData?: GraphQLFillerData<typeof barQuery>,
} = {}) {
return {
fooQuery: fillGraphQL(fooQuery, {data: 'default', ...fooData}),
barQuery: fillGraphQL(barQuery, {data: 'default', ...barData}),
};
}
```
Now we can easily call `createFilledOperations` with either static …

[graphql-fixtures] adding new GraphQLFillerData type construct

---

packages/graphql-fixtures/src/fill.ts
packages/graphql-fixtures/tests/fill.test.ts

The way this was implemented before we would get only two possible sizes for the random list.
For example if I were to use list with `list([2,6])`, where we do `size[Math.round(Math.random())]` the only two possible indexes are 0 and 1, so `finalSize` in this case would be either 2 or 6, but would never be anything in between. So sometimes we would have an array of size 2, sometimes of size 6, but nothing else.
In my proposed implementation I take a random number from 0 to the difference between min and max by multiplying `Math.random` with that difference and add the result to the min value. This would give us a random number between the two values as advertised in the docs:
> an array randomly sized in that range
I hope this helps.
Regards.

Fix random sizing of lists

---

packages/graphql-mini-transforms/README.md
packages/graphql-mini-transforms/jest-simple.js
packages/graphql-mini-transforms/package.json
packages/graphql-mini-transforms/src/document.ts
packages/graphql-mini-transforms/src/jest-simple.ts
packages/graphql-mini-transforms/src/webpack.ts
packages/graphql-mini-transforms/tests/webpack.test.ts
packages/graphql-typed/index.ts
packages/graphql-typescript-definitions/README.md
packages/graphql-typescript-definitions/src/cli.ts
packages/graphql-typescript-definitions/src/index.ts
packages/graphql-typescript-definitions/src/print/document/context.ts
packages/graphql-typescript-definitions/src/print/document/index.ts
packages/graphql-typescript-definitions/src/types.ts
packages/graphql-typescript-definitions/test/document.test.ts
yarn.lock

This PR introduces a new format that a GraphQL document can be exported in. This format, which I've called `simple` (open to other names; also considered `raw`/ `no-ast`), does not contain the full AST representation of the query (so, no longer a `DocumentNode`). Instead, it has the minimal amount of information needed by a GraphQL client that does a query-based cache: `id` (a hash of the minified document source; useful as a cache key), `source` (the minified document source; need to send as part of network requests), and `name` (the first operation name in the source; need to send as part of network requests). This representation is significantly smaller than the full AST.
While I was here, I also changed the webpack output of a `.graphql` file to be the result of `JSON.parse`ing a …

"Simple" document types

---

packages/graphql-typescript-definitions/src/cli.ts
packages/graphql-typescript-definitions/src/index.ts
packages/graphql-validate-fixtures/src/cli.ts

I introduced a change that incorrectly imported chalk. See https://github.com/chalk/chalk/issues/399
This PR fixes it.

Fix chalk import to work with esModuleInterop

---

packages/graphql-typescript-definitions/src/print/schema/index.ts
packages/graphql-typescript-definitions/test/schema.test.ts

Fixes https://github.com/Shopify/graphql-tools-web/issues/117
As @patsissons mentioned:  "When generating the schema types module, the generated `index.ts` will contain interleaved `import` and `export` statements rather than a properly formed module that places all imports first and all exports second"
This fix updates `generateSchemaTypes` to group import and export statements and concat them at the end so that the generated file is in compliance with `import/first` eslint rule.
**Example**
Before:
```ts
import { Season } from "./Season";
export { Season };
import { Episode } from "./Episode";
export { Episode };
export type Date = string;
export interface InputOne {
dates: (Date | null)[];
episodes: Episode[];
season: Season;
inputs?: (InputTwo | null)[] | null;
}
```
After:
```ts …
```

Update generateSchemaTypes to group import and export statements

---

packages/graphql-typescript-definitions/README.md

Hi there! Firstly, thank you for this project. As I was getting this set up for a project of my own, I noticed that there was a slight error in the example `.graphqlconfig` in the README. The `includes` field should be an array of globs, not just a string. The downstream `graphql-config` package basically does a call that looks like `(this.config.includes || []).map(...)`, and this obviously fails in the case of just a single string `includes` field. 
Let me know if I need to do anything else to get this small change through. Thanks!

Update README.md with correct `.graphqlconfig`

---

packages/graphql-typescript-definitions/CHANGELOG.md
packages/graphql-typescript-definitions/README.md
packages/graphql-typescript-definitions/src/print/schema/index.ts
packages/graphql-typescript-definitions/test/schema.test.ts

I have a custom type named `Seconds` in my GraphQL schema that is really just an `Int`. The current implementation of `graphql-typescript-definitions` doesn't allow this. So here's a PR that lets you alias any built-in JS type.
The `package` property in custom-scalars is now optional. If left out then no import will be performed, and the `name` is assumed to be a globally available type.
e.g.
--custom-scalars '{"Seconds": {"name": "number"}}'
Will become:
export type Seconds = number;

Allow custom scalars that alias built-in types

---

packages/graphql-typescript-definitions/CHANGELOG.md
packages/graphql-typescript-definitions/src/print/schema/index.ts
packages/graphql-typescript-definitions/test/schema.test.ts

In the unlikely event that a schema is borderline empty and wouldn't
produce any types we previously outputted a blank file. Which causes
type checking with isolatedModules enabled to fail because a blank file
is ambigiuous - it could be a script or a module. This change ensures
that if a file would otherwise be blank we output a `export {}` to make
it clear that the file should be treated as an es modules file.

Always output a valid es module file
